apiVersion: apps/v1
kind: Deployment
metadata:
  name: vpromq01
  labels:
    app: vpromq01							# rmq deployment label
spec:
  selector:
    matchLabels:
      app: vpromq01
  replicas: 1
  template:
    metadata:
      labels:
        app: vpromq01						# pod label
    spec:
      containers:
      - name: vpromq01
        image: rabbitmq 					# official image no need of customization
        ports:
        - name: vpromq01-port               # name of rmq container port
          containerPort: 15672              # listening on this port
        env: 
        - name: RABBITMQ_DEFAULT_PASS		# this is the default valiable as per official RabbitMQ image documentation on docker hub
          valueFrom:
            secretKeyRef:
              name: app-secret				# secret name defined in secret.yml
              key: rmq-pass				    # value from the rmq-pass will be fetched from secrets and assigned to name RABBITMQ_DEFAULT_PASS
        - name: RABBITMQ_DEFAULT_USER		# guest username as per app.properties file
          value: "guest"					# guest password as per app.properties file, password kept in secrets  